name = "status"
type = "javascript"
workers_dev = true
account_id = "9bd385412f8007bf1528977393e9ae0b"
compatibility_date = "2021-10-27"

kv_namespaces = [
    { binding = "STATUS", id = "5653c991eb264a7e8a2c2f999f939acf" }
]

[triggers]
crons = ["*/5 * * * *"]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
