name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm install
      - run: npm run build

  deploy:
    needs: [ build ]
    if: github.event_name != 'pull_request'

    environment:
      name: Cloudflare Workers
      url: https://status.the-morpheus.workers.dev

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm install

#      - name: Metadata
#        id: meta
#        run: echo "::set-output name=version::${{ github.sha }}"

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
